version: '3.8'

services:
  # バックエンド
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AZURE_SQL_URL=jdbc:sqlserver://todoapp-serverinsu.database.windows.net:1433;database=todoapp-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - AZURE_SQL_USERNAME=todo-admin@todoapp-serverinsu
      - AZURE_SQL_PASSWORD=R!n1351206
      - AZURE_SQL_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - maven-repo:/root/.m2
    networks:
      - app-network

  # フロントエンド開発サーバー
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  maven-repo: 