@baseUrl = https://todoapp-rinsu-g5b7f6argrd5gxc3.japaneast-01.azurewebsites.net/api/todos

### Todo一覧取得テスト
GET {{baseUrl}}/list
Accept: application/json

### Todo追加テスト
POST {{baseUrl}}/add
Content-Type: application/json

{
    "title": "テストタスク2",
    "deadline": "2025-05-01"
}

### Todo削除テスト
POST {{baseUrl}}/delete/1
Content-Type: application/json

### テストAPI
POST {{baseUrl}}/test
Accept: application/json